language: python
python:
- 3.5
script:
- python setup.py build
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: GpKjgPtcCu5fpEGuxvKR1q85tfccFRw/QZIJ2XOfvb0Pxa+3up16Z1GCAmWmkxO+dcddfxt1UG5oKdRfQElKeHea26FoKc8Pj5qmDewjQdA+3U5TmX6TEeJSt+iDa4Y48By/FqlAY5Jlc9Dj0MS93ET/YCbYUcBzq9axPmrfPpTBAmmCvWm/HFO7JzEtF38EIjzzScHF/dBlevWm0oK7jnXhnsF5U+3PkFwlkTWCIGZHUSyjM3B7FDTBGXFBOMmueCgnTni6uOqjAr1rB4LP5idgs/j8mKWW87DkKKFQbJZvlXMwqCZSNwKDhC1jv735jheyKptiRQgPc8jsYiRbj2i/nEKgPh9qGQ7xWEXg/GaOtgzO7P1akq3KN4MSlA0GhC/H4mXW3EMUWkiOPV/gcFElztRNyPCbk1MFNzBWCRCcLDIYx1JXuqfC2f/hm3eYnGju3A1pYBHgL0V6JJWODSc3CuVwoVjV3qfQxJukgwX799wFeEouwW1MrkTj55n0d7OKg8yd7Z1mwnn9pcYTuJnbxVJKQVQLI9xH+mMc51p7ZcKGcdYmTALTeWq4j50a5tlG4RhacU2PSHGClIEKRpDVzetiUH05CrbGIs+8g1MMzjVfgrSZX0Rwf03l9lepBlf+1imoogF5cCb4j5vY3d6FsglkarcGbm3ah18NhGg=
  on:
    tags: true
    repo: ovh/python-logging-gelf
